[theme]
primaryColor = "#16191F"
backgroundColor = "#F0F2F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#16191F"
font = "sans serif"
base = "light"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true